# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c295ff4e22d6632458b6e41ad7c1050f9ce036a4ee399715109c0c3eda98cad00299439bb62bbfb5b3ebe80e83d005b8393bab836af85629a85b391bef83af4b

test:
  secret_key_base: 59bddbadff71d9406bd799ddf5318c5d58dec76244c990f044b44642ab70169efd9de9288d3af93bfdbd6d1b2c2e635759fc171e5bdd84aab24779b12a68a51c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
